CREATE DATABASE tarea5_fitnessapp;
CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50),
email VARCHAR(80) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL
);
CREATE TABLE trains(
id INT AUTO_INCREMENT PRIMARY KEY,
duration VARCHAR (20),
exercises VARCHAR(100),
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
user_id INT,
FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE goals(
id INT AUTO_INCREMENT PRIMARY KEY,
goal_name VARCHAR(40),
deadline TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
user_id INT,
FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE recomendations(
id INT AUTO_INCREMENT PRIMARY KEY,
exercise_name VARCHAR(50),
user_id INT,
FOREIGN KEY (user_id) REFERENCES users(id)
);